### ISSUE TITLE
Error: Cannot find module 'vue-stripe-elements-plus'

### ISSUE THREAD

**Issue by GORobert** [getspooky/yaldash#25]
Hey, i installed laravel 7, then the ui `composer require laravel/ui` and then laradash `composer require yal/laraveldash` using installation guide.
I was able go to /Dashboard, but i was missing styles and scripts. I copied them from `/vendor/yal/laraveldash/src/published` to `/public/published` . Is it the right way or did i miss something? if that's right good to add that to installation guide.
Now i'm almost there but going to "Add Post" in menu i see no content, just error in console:
`Error: Cannot find module 'vue-stripe-elements-plus`

**Comment by oliuz** [comment]
Hi @GORobert 

To correct that, you must export the assets as follows:
`php artisan vendor:publish --provider="Yasser\LaravelDashboard\DashboardServiceProvider" --tag="laravelDash-assets"`
