### ISSUE TITLE
☕️ LaravelDash `v1.0.2` 

### ISSUE THREAD

**Issue by getspooky** [getspooky/yaldash#29]
I think it's time to work on a new version of laravelDash `v1.0.2` : 
## Features
- Simple and pretty UI
- Integrate Chat discussion 
- Code Refactoring

what do you think 🤔 ??

**Comment by oliuz** [comment]
It is a very good idea, for example, you can refactor the LaravelPostController using Form Requests, for example.

**Comment by getspooky** [comment]
@oliuz  Yes I agree , so we can work together on that ??

**Comment by oliuz** [comment]
@getspooky Of course, in the same way the other methods of said controller.

**Comment by getspooky** [comment]
@oliuz The main goal behind creating a new version of laravelDash is to create a tool for building admin panels.
I was looking for a simple and pretty UI , what do you think about [that](https://uxcandy.co/demo/label-free/preview/demo_1/index.html) ??

**Comment by oliuz** [comment]
@getspooky Simple but I liked it!

> a new version of laravelDash is to create a tool for building admin panels

By this you mean something like https://2019.quickadminpanel.com/...?

**Comment by getspooky** [comment]
We will keep the same idea by we will add other features

**Comment by oliuz** [comment]
@getspooky The package will have to become a multi-tenant type for that reason.
