### ISSUE TITLE
Don't Work 

### ISSUE THREAD

**Issue by Sebastiangperez** [getspooky/yaldash#3]
I followed all the steps but don't work, routes didn't work. 
running Laravel 5.8

**Comment by Sebastiangperez** [comment]
> I followed all the steps but don't work, routes didn't work.
> running Laravel 5.8
I just copy and paste the routes from the vendor directories but few things still missing.
Maybe it will be nice if you can give us not just the package , but also an example project.

**Comment by getspooky** [comment]
You should generate Authentication run  this command : php artisan make:auth
https://medium.com/@yasserameur/build-laravel-web-applications-faster-than-ever-234dfb802b5

**Comment by Sebastiangperez** [comment]
> You should generate Authentication run this command : php artisan make:auth
> https://medium.com/@yasserameur/build-laravel-web-applications-faster-than-ever-234dfb802b5

Yes , i did that , but also routes didn't work until i copied the stuff , i think there is a bug o something with Laravel 5.8. 
Do i need to have any data in my database? i mean ,Posts something like that ? 
i followed each step.

**Comment by getspooky** [comment]
thanks , I will make a tutorial

Le mar. 16 avr. 2019 à 21:57, Sebastiangperez <notifications@github.com> a
écrit :

**Comment by oliuz** [comment]
Hi,
I had the same problem, I'm already working on that, as soon as I finish I can perform the pull request

**Comment by brainlet-ali** [comment]
Same HERE (Laravel 5.8)

**Comment by onyx26** [comment]
Glad it's not just me! New project, as per the instructions (as I'm only testing), and there are no routes and Trait 'App\UserRelation' not found.

This package looks promising from what I've seen in the docs.

**Comment by getspooky** [comment]
Maybe you do not understand how to install it :
follow these steps : 
1:Create the Laravel application
I will be using via composer to create new project
composer create-project --prefer-dist laravel/laravel blog
2 : Configuration
Firstly, make sure to create a new database and add your database credentials to your .env file 
3 :  Install and Configure laravelDash
you can include the laravelDash package with the following command:
composer require yal/laraveldash
If you are using LaravelDash with Laravel 5.3 or 5.4, add LaravelDash’s service provider in your application’s config/app.php file:
Yasser\LaravelDashboard\DashboardServiceProvider::class,
4 : Publishing the LaravelDash config file and Migrating the database tables into your application
php artisan LaravelDash:install 
5 :  Adding UserRelation 
go to App\User.php and add UserRelation 

use Yasser\LaravelDashboard\Traits\UserRelation;

class User extends Authenticatable
{
    use Notifiable,UserRelation;

}

**Comment by jmdollosa** [comment]
Same problem here, just trying out LaravelDash but i cant make it work.
Followed the steps below on a new app created.
My version is 5.8.13.

Will try again the second time

1:Create the Laravel application
I will be using via composer to create new project
composer create-project --prefer-dist laravel/laravel blog
2 : Configuration
Firstly, make sure to create a new database and add your database
credentials to your .env file
3 : Install and Configure laravelDash
you can include the laravelDash package with the following command:
composer require yal/laraveldash
If you are using LaravelDash with Laravel 5.3 or 5.4, add LaravelDash’s
service provider in your application’s config/app.php file:
Yasser\LaravelDashboard\DashboardServiceProvider::class,
4 : Publishing the LaravelDash config file and Migrating the database
tables into your application
php artisan LaravelDash:install
5 : Adding UserRelation
go to App\User.php and add UserRelation

use Yasser\LaravelDashboard\Traits\UserRelation;

class User extends Authenticatable
{
use Notifiable,UserRelation;

**Comment by jmdollosa** [comment]
Works now. :) It would help if you specify the default site urls in the
wiki , so they dont need to look into the code to figure out what routes
are being generated.
(e.g http://mywebsite.com/Dashboard - For dashboard)

**Comment by onyx26** [comment]
> Maybe you do not understand how to install it :
> follow these steps :
> 1:Create the Laravel application
> I will be using via composer to create new project
> composer create-project --prefer-dist laravel/laravel blog
> 2 : Configuration
> Firstly, make sure to create a new database and add your database credentials to your .env file
> 3 : Install and Configure laravelDash
> you can include the laravelDash package with the following command:
> composer require yal/laraveldash
> If you are using LaravelDash with Laravel 5.3 or 5.4, add LaravelDash’s service provider in your application’s config/app.php file:
> Yasser\LaravelDashboard\DashboardServiceProvider::class,
> 4 : Publishing the LaravelDash config file and Migrating the database tables into your application
> php artisan LaravelDash:install
> 5 : Adding UserRelation
> go to App\User.php and add UserRelation
> 
> use Yasser\LaravelDashboard\Traits\UserRelation;
> 
> class User extends Authenticatable
> {
> use Notifiable,UserRelation;
> 
> }

So following those instructions, it works fine. The thing I missed was not adding "use Yasser\LaravelDashboard\Traits\UserRelation;", but I also note you've improved the install process (php artisan LaravelDash:install) but haven't yet updated the documentation.  

I'd suggest you mention the default route, as jmdollosa says, and create a default logon account. Is there a way to make someone an admin role? Can't see anything.

And I'm a bit confused - if this is an admin panel with CRUD, where do I create a new CRUD entity? "LaravelDash:resource" only seems to create a new View. Sorry - I'm fairly new to all this.

**Comment by obiefy** [comment]
Please share with us the specific exception that occurs when installing this package

**Comment by ThistleApps** [comment]
I created a Laravel 5.8 project and have the same issue.  

`C:\xampp\htdocs\memberstudio>composer require yal/laraveldash
Using version dev-master for yal/laraveldash
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yal/laraveldash dev-master -> satisfiable by yal/laraveldash[dev-master].
    - Conclusion: remove laravel/framework v5.8.18
    - Conclusion: don't install laravel/framework v5.8.18
    - yal/laraveldash dev-master requires cartalyst/stripe-laravel 9.0.* -> satisfiable by cartalyst/stripe-laravel[9.0.x-dev, v9.0.0].
    - cartalyst/stripe-laravel 9.0.x-dev requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-d
ev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9]
.
    - cartalyst/stripe-laravel v9.0.0 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev,
 v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.18].
    - don't install illuminate/support 5.7.17|don't install laravel/framework v5.8.18
    - don't install illuminate/support 5.7.18|don't install laravel/framework v5.8.18
    - don't install illuminate/support 5.7.19|don't install laravel/framework v5.8.18
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.0|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.1|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.10|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.11|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.15|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.2|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.20|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.21|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.22|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.23|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.26|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.27|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.28|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.3|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.4|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.5|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.6|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.7|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.8|don't install laravel/framework v5.8.18
    - don't install illuminate/support v5.7.9|don't install laravel/framework v5.8.18
    - Installation request for laravel/framework (locked at v5.8.18, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.18].


Installation failed, reverting ./composer.json to its original content.
`

**Comment by AshrafBasry** [comment]
@ThistleApps 
There is pull request #7 fixing this issue waiting for review .

**Comment by ThistleApps** [comment]
@AshrafBasry Sorry but is this to say it is fixed?

**Comment by AshrafBasry** [comment]
@ThistleApps
Yes it is .

**Comment by getspooky** [comment]
Solved
