### ISSUE TITLE
Route login not defined

### ISSUE THREAD

**Issue by RodrigoGalter** [getspooky/yaldash#31]
I followed reame instructions to install, but when i access the url '**Dashboard**' I get this error.

![image](https://user-images.githubusercontent.com/2292422/88094474-093a2980-cb6a-11ea-85e3-770aa1de5bdd.png)

I trying install in laravel 6 and 7.

The command '**php artisan make:auth**' does not work in laravel 6 and 7

**Comment by guywarner** [comment]
@RodrigoGalter the auth ui items were moved out of the main laravel repo:

https://laravel.com/docs/7.x/authentication#authentication-quickstart
