### ISSUE TITLE
Moving laravelDash to an organization 

### ISSUE THREAD

**Issue by getspooky** [getspooky/yaldash#33]
Hi, I am working on a new version `1.0.2` of `laravelDash` so I was thinking it could be a good idea to move `laravelDash` to an organization.

**Comment by oliuz** [comment]
Hi, It would be an excellent idea, I am also working on some things to upload to the repo

**Comment by getspooky** [comment]
@oliuz Please feel free to push all features to the `version-1.0.2` branch
