### ISSUE TITLE
Making video tutorial explain everything about laravelDash

### ISSUE THREAD

**Issue by getspooky** [getspooky/yaldash#42]

**Comment by oliuz** [comment]
Hi @getspooky 

It is a good idea. I'm currently small refactoring in the user settings view and other changes, I also edit the readme file to provide a little laravelDash installation guide.

What do you think?

**Comment by getspooky** [comment]
@oliuz I appreciate you work. Can you do a laraveDash tutorial ?

**Comment by oliuz** [comment]
Yes, how to install LaravelDash in a fresh Laravel app.
