### ISSUE TITLE
Dont work 'Cartalyst\Stripe\Laravel\StripeServiceProvider' not found

### ISSUE THREAD

**Issue by Taalaybek** [getspooky/yaldash#5]
I try to install the dashboard but during installation and after i get errors
https://prntscr.com/nw0tgz
https://prntscr.com/nw0tnu

**Comment by nowendwell** [comment]
Same here. Reverts install due to the error.

**Comment by getspooky** [comment]
I'm already working on that, as soon as I finish I can perform the pull request but you can avoid this error  by install composer require cartalyst/stripe-laravel before laravelDash

**Comment by Taalaybek** [comment]
after installing cartalyst/stripe-laravel and run LaravelDash:insall i have new errors with sql

**Comment by getspooky** [comment]
send me errors

**Comment by AshrafBasry** [comment]
i think this is the problem
` 
"require-dev": {
        "laravel/browser-kit-testing": "^5.1",
        "phpunit/phpunit": "^7.0",
        "cartalyst/stripe-laravel": "9.0.*"
    }
`
you have to move  cartalyst/stripe-laravel to require
