### ISSUE TITLE
Dashboard not found

### ISSUE THREAD

**Issue by ugintl** [getspooky/yaldash#75]
After installation, when I go to mysite.com/dashboard it says "Not Found". I am on laravel 8

**Comment by oliuz** [comment]
Hi @ugintl 

This issue is resolved with the PR #76

**Comment by ugintl** [comment]
But is have not been merged I think. How I should apply it to the yaldash repo I have on my computer? `git pull`?

**Comment by oliuz** [comment]
Hi @ugintl 

The new package update has already been published, the issue is closed.
